

services:
  postgres:
    image: postgres:15
    container_name: ton-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tondb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ton-net

volumes:
  pgdata:

networks:
  ton-net:
